#!/usr/bin/env python3
"""Regenerate internal/push/testdata/parity/goldens.json by running the REAL
data-ingestors validators over the parity fixture cases.

This is the Python half of the validator-parity harness (backend#828 P3):
the CLI's local preflight (internal/push/preflight.go) previews the
in-cluster validators, and parity_golden_test.go pins that the two sides
agree case-by-case. When the ingestor's rules change, re-run this and
commit the diff — a changed verdict then fails the Go test until the
preview is consciously updated.

Usage:
    DATA_INGESTORS_DIR=~/path/to/data-ingestors python3 scripts/gen-validator-goldens.py

DATA_INGESTORS_DIR must point at a checkout of tracebloc/data-ingestors
with its dependencies importable (its own .venv works:
    ~/repos/data-ingestors/.venv/bin/python scripts/gen-validator-goldens.py
also does the trick — the script only needs pandas + Pillow, no MySQL).

Verdicts are recorded at the accept/reject level, not message-text level —
error copy may drift harmlessly; verdicts may not. TableNameValidator and
DuplicateValidator are skipped (they check cluster-side state — the table
name is validated separately by both sides, and destination-duplicate
handling is the cli#70 guard's territory, not a data-hygiene rule).
"""

import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PARITY = os.path.join(HERE, "..", "internal", "push", "testdata", "parity")

di = os.environ.get("DATA_INGESTORS_DIR", "")
if di:
    sys.path.insert(0, os.path.abspath(di))

try:
    from tracebloc_ingestor.utils.validators_mapping import map_validators
    from tracebloc_ingestor.config import Config
    from tracebloc_ingestor.ingestors import preflight
except ImportError as exc:  # pragma: no cover
    sys.exit(
        f"can't import the data-ingestors package ({exc}).\n"
        "Set DATA_INGESTORS_DIR to a checkout, or run with its venv python."
    )

SKIP = {"TableNameValidator", "DuplicateValidator"}
ANSI = re.compile(r"\x1b\[[0-9;]*m")


def infer_schema(csv_path):
    """Mirror the CLI's inference shape: every trimmed header column typed —
    the schema content doesn't matter for these validators, membership does.
    Read with pandas (BOM-stripping) exactly like the CLI's header reader."""
    import pandas as pd

    cols = list(pd.read_csv(csv_path, nrows=0, encoding="utf-8").columns)
    return {str(c).strip(): "VARCHAR(255)" for c in cols}


def run_case(case):
    case_dir = os.path.join(PARITY, "cases", case["name"])
    csv_path = os.path.join(case_dir, case["csv"])

    if True:  # (kept indented for a small diff; no tempdir needed — DuplicateValidator is skipped)
        cfg = Config(SRC_PATH=case_dir, TABLE_NAME="parity_t")
        options = {"label_column": case.get("label_column", "label")}
        if case.get("extension"):
            options["extension"] = case["extension"]
        if case.get("target_size"):
            options["target_size"] = case["target_size"]
        if case["category"].startswith(("tabular", "time_")):
            try:
                schema = infer_schema(csv_path)
            except Exception:
                schema = {}
            options["schema"] = schema
            options["full_schema"] = schema

        errors = []
        try:
            preflight.check_csv_encoding(csv_path)
        except Exception as exc:
            errors.append(f"csv-encoding: {exc}")

        for v in map_validators(case["category"], options, cfg):
            if type(v).__name__ in SKIP:
                continue
            try:
                res = v.validate(csv_path)
                if not res.is_valid:
                    errors.extend(
                        f"{type(v).__name__}: {ANSI.sub('', str(e)).replace(case_dir + os.sep, '')}"
                        for e in res.errors
                    )
            except Exception as exc:  # a raising validator is a rejection too
                errors.append(f"{type(v).__name__}: raised {exc}")

    return {
        "verdict": "reject" if errors else "accept",
        "errors": errors[:6],
    }


def main():
    with open(os.path.join(PARITY, "cases.json")) as f:
        manifest = json.load(f)

    goldens = {}
    for case in manifest["cases"]:
        goldens[case["name"]] = run_case(case)
        print(f"  {case['name']:24s} → {goldens[case['name']]['verdict']}")

    out = os.path.join(PARITY, "goldens.json")
    with open(out, "w") as f:
        json.dump(
            {
                "_comment": "GENERATED by scripts/gen-validator-goldens.py from the REAL "
                "data-ingestors validators — do not hand-edit. Regenerate when the "
                "ingestor's rules change; parity_golden_test.go pins these.",
                "verdicts": goldens,
            },
            f,
            indent=2,
            sort_keys=True,
        )
        f.write("\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
